name: RandomTeleport
main: com.shanebeestudios.rtp.RandomTeleport
version: '${project.version}'
api-version: 1.13
commands:
  rtp:
    description: Main command for RTP
    permission: randomteleport.command.rtp
