name: RandomTeleport
main: com.shanebeestudios.rtp.RandomTeleport
version: @version@
api-version: 1.13
author: ShaneBee
website: https://github.com/ShaneBeee/RandomTeleport
description: A simple plugin to teleport a player to a random location

